/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package machinemaintenanceautomationsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LEGION
 */
public class inventory extends javax.swing.JFrame {
    
    /**
     * Creates new form inventory
     */
    public inventory() {
        initComponents();
        load();
    }
         public void load()
         { try
        {
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost/inventory","root","");
            PreparedStatement pst=con .prepareStatement("select * from store");
            ResultSet rs=pst.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getInt("PartID"),rs.getString("PartName"),rs.getInt("PartPrice"),rs.getInt("PartQuantity"),rs.getString("PartD")};
                tm.addRow(o);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }

   
                   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JPP = new javax.swing.JTextField();
        JPq = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPI = new javax.swing.JTextField();
        jPN = new javax.swing.JTextField();
        jPD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JBE = new javax.swing.JButton();
        JBS = new javax.swing.JButton();
        JBD = new javax.swing.JButton();
        JBR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Inventory System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPPActionPerformed(evt);
            }
        });
        jPanel2.add(JPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 230, 38));

        JPq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPqActionPerformed(evt);
            }
        });
        jPanel2.add(JPq, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 240, 36));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PartID:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 47, 86, 38));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PartQuantity");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 38));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PartName");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 118, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PartD");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 129, 37));
        jPanel2.add(jPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 230, 38));

        jPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPNActionPerformed(evt);
            }
        });
        jPanel2.add(jPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 230, 38));

        jPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPDActionPerformed(evt);
            }
        });
        jPanel2.add(jPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 260, 70));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PartPrice:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 38));

        JBE.setBackground(new java.awt.Color(102, 255, 0));
        JBE.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JBE.setForeground(new java.awt.Color(255, 255, 255));
        JBE.setText("edit");
        JBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEActionPerformed(evt);
            }
        });
        jPanel2.add(JBE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 96, -1));

        JBS.setBackground(new java.awt.Color(102, 255, 51));
        JBS.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JBS.setForeground(new java.awt.Color(255, 255, 255));
        JBS.setText("add");
        JBS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBSMouseClicked(evt);
            }
        });
        JBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSActionPerformed(evt);
            }
        });
        jPanel2.add(JBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        JBD.setBackground(new java.awt.Color(102, 255, 0));
        JBD.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JBD.setForeground(new java.awt.Color(255, 255, 255));
        JBD.setText("Delete");
        JBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDActionPerformed(evt);
            }
        });
        jPanel2.add(JBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        JBR.setBackground(new java.awt.Color(102, 255, 0));
        JBR.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JBR.setForeground(new java.awt.Color(255, 255, 255));
        JBR.setText("Reset");
        JBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRActionPerformed(evt);
            }
        });
        jPanel2.add(JBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 110, -1));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PartID", "PartName", "PartPrice", "PartQuantity", "PartD"
            }
        ));
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEActionPerformed
        // TODO add your handling code here:
   
         try{
            Class.forName("com.mysql.jdbc.Driver");
            //here sonoo is database name, root is username and password
            try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost/inventory","root","")) {
            //here sonoo is database name, root is username and password
             DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            int selected = jTable1.getSelectedRow();
            
            String value =(jTable1.getModel().getValueAt(selected, 0).toString());
                    Statement stmt=con.createStatement();
            
            String s= "UPDATE store  set PartName=?,PartPrice=?,PartQuantity=?,PartD=?  where PartID="+value;
            PreparedStatement ps=con.prepareStatement(s);
        
            ps.setString(1,jPN.getText());
            ps.setString(2,JPP.getText());
            ps.setString(3,JPq.getText());
            ps.setString(4,jPD.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"edited successfully");
            load();
            jPI.setText("");
             jPN.setText("");
              JPP.setText(""); 
               JPq.setText("");
                jPD.setText("");
              
        }   catch (SQLException ex) {
            Logger.getLogger(employeeform.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        catch(  ClassNotFoundException e){ System.out.println(e);}
              JBS.setEnabled(true);
    }//GEN-LAST:event_JBEActionPerformed

    private void JPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPPActionPerformed

    private void JPqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPqActionPerformed

    private void jPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPNActionPerformed

    private void jPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPDActionPerformed

    private void JBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //here sonoo is database name, root is username and password
            try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost/inventory","root","")) {
            //here sonoo is database name, root is username and password
            Statement stmt=con.createStatement();
            String s="insert into store(PartID,PartName,PartPrice,PartQuantity,PartD) values(?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(s);
            ps.setString(1,jPI.getText());
            ps.setString(2,jPN.getText());
            ps.setString(3,JPP.getText());
            ps.setString(4,JPq.getText());
            ps.setString(5,jPD.getText());
            ps.execute();
            JOptionPane.showMessageDialog(this,"added successfully");
            load();
            jPI.setText("");
             jPN.setText("");
              JPP.setText(""); 
               JPq.setText("");
                jPD.setText("");
              
        }   catch (SQLException ex) {
            Logger.getLogger(employeeform.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        catch(  ClassNotFoundException e){ System.out.println(e);}
         JBS.setEnabled(true);  
    }//GEN-LAST:event_JBSActionPerformed

    private void JBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRActionPerformed
        // TODO add your handling code here:
         jPI.setText("");
             jPN.setText("");
              JPP.setText(""); 
               JPq.setText("");
                jPD.setText("");
               JBS.setEnabled(true);
    }//GEN-LAST:event_JBRActionPerformed

    private void JBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDActionPerformed
        // TODO add your handling code here:
       
            try{
            Class.forName("com.mysql.jdbc.Driver");
            //here sonoo is database name, root is username and password
            try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost/inventory","root","")) {
            //here sonoo is database name, root is username and password
            Statement stmt =con.createStatement();
            String s="DELETE FROM store WHERE PartID=?";
            PreparedStatement ps=con.prepareStatement(s);
            ps.setString(1,jPI.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"deleted successfully");
            load();
            jPI.setText("");
             jPN.setText("");
              JPP.setText(""); 
               JPq.setText("");
                jPD.setText("");
           
          
  
            }catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);}
       }catch(  ClassNotFoundException e){ System.out.println(e);}
        JBS.setEnabled(true);
    }//GEN-LAST:event_JBDActionPerformed

    private void JBSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JBSMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            int selected =jTable1.getSelectedRow();
            
            jPI.setText(tm.getValueAt(selected, 0).toString());
            jPN.setText(tm.getValueAt(selected, 1).toString());
            JPP.setText(tm.getValueAt(selected, 2).toString());
            JPq.setText(tm.getValueAt(selected, 3).toString());
            jPD.setText(tm.getValueAt(selected, 4).toString());
              JBS.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBD;
    private javax.swing.JButton JBE;
    private javax.swing.JButton JBR;
    private javax.swing.JButton JBS;
    private javax.swing.JTextField JPP;
    private javax.swing.JTextField JPq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jPD;
    private javax.swing.JTextField jPI;
    private javax.swing.JTextField jPN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
